version: "3.8"
# run using docker compose up --build
services:
  app:
    image: nodeapp:local
    build:
      context: ./
    ports:
      - "3000:3000"
    env_file:
      - .env
    depends_on:
      mysql:
        condition: service_healthy
    networks:
      - mynetwork
    user: "appuser" # non-root user

  mysql:
    image: mysql:5.7
    env_file:
      - .env
    volumes:
      - ./mysql:/docker-entrypoint-initdb.d
    networks:
      - mynetwork
    healthcheck:
      test: '/usr/bin/mysql --user=root --password=$$MYSQL_ROOT_PASSWORD -h mysql -P 3306 $$MYSQL_DATABASE --execute "SHOW DATABASES;"'
      interval: 20s
      timeout: 2000s
      retries: 10

networks:
  mynetwork: