version: "3.8"
# run using docker compose up --build
services:
  app:
    build:
      context: ./
    ports:
      - "3000:3000"
    env_file:
      - .env
    depends_on:
      mysql:
        condition: service_healthy
    networks:
      - mynetwork
    user: "appuser" # non-root user

  mysql:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: password # pass by secrets after testing
      MYSQL_DATABASE: releases_db
    ports:
      - "3306:3306" # Expose MySQL port remove after local testing
    volumes:
      - ./mysql:/docker-entrypoint-initdb.d
    networks:
      - mynetwork
    healthcheck:
      test: '/usr/bin/mysql --user=root --password=password -h mysql -P 3306 releases_db --execute "SHOW DATABASES;"' # passwords should be passed by secrets after testing
      interval: 20s
      timeout: 2000s
      retries: 10

networks:
  mynetwork: