name: CI

on:
  push:
    branches:
      - master

jobs:
  ci-build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Create .env file
        run: |
          touch .env
          echo DB_HOST=${{ secrets.DB_HOST }} >> .env
          echo DB_USER=${{ secrets.DB_USER }} >> .env
          echo DB_PASSWORD=${{ secrets.DB_PASSWORD }} >> .env
          echo DB_DATABASE=${{ secrets.DB_DATABASE }} >> .env
          echo API_KEY=${{ secrets.API_KEY }} >> .env
          echo MYSQL_ROOT_PASSWORD=${{ secrets.MYSQL_ROOT_PASSWORD }} >> .env
          echo MYSQL_DATABASE=${{ secrets.MYSQL_DATABASE }} >> .env

      - name: Docker Compose Up
        run: docker compose up --build -d
      
      - name: Run Trivy Container scan
        uses: aquasecurity/trivy-action@0.20.0
        with:
          image-ref: nodeapp:local
          format: 'table'
          exit-code: '1'
          ignore-unfixed: true
          vuln-type: 'os,library'
          severity: 'CRITICAL,HIGH'

      - name: Run Trivy scanner in SBOM mode (Output)
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: 'image'
          format: 'table'
          hide-progress: true
          image-ref: nodeapp:local
          output: trivy.md

      - name: Publish Trivy Output to Summary
        run: |
          if [[ -s trivy.md ]]; then
            {
              echo "### Security SBOM Output"
              echo "<details><summary>Click to expand</summary>"
              echo ""
              echo '```'
              cat trivy.md
              echo '```'
              echo "</details>"
            } >> $GITHUB_STEP_SUMMARY
          fi    

      - name: Wait for the docker to start
        run: sleep 60

      - name: Simple API Endpoint Test
        run: |
          curl -H "x-api-key: ${{ secrets.API_KEY }}" http://localhost:3000/drift