name: CI

on:
  push:
    branches:
      - master

jobs:
  ci-build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Create .env file
        run: |
          touch .env
          echo DB_HOST=${{ secrets.DB_HOST }} >> .env
          echo DB_USER=${{ secrets.DB_USER }} >> .env
          echo DB_PASSWORD=${{ secrets.DB_PASSWORD }} >> .env
          echo DB_DATABASE=${{ secrets.DB_DATABASE }} >> .env
          echo API_KEY=${{ secrets.API_KEY }} >> .env
          echo MYSQL_ROOT_PASSWORD=${{ secrets.MYSQL_ROOT_PASSWORD }} >> .env
          echo MYSQL_DATABASE=${{ secrets.MYSQL_DATABASE }} >> .env

      - name: Docker Compose Up
        run: docker compose up --build

      - name: Wait for the docker to start
        run: sleep 60

      - name: Simple API Endpoint Test
        run: |
          curl -H "x-api-key: ${{ secrets.API_KEY }}" http://localhost:3000/drift