name: CI

on:
  push:
    branches:
      - master

jobs:
  Test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Create .env file
        run: |
          touch .env
          echo DB_HOST=${{ secrets.DB_HOST }} >> .env
          echo DB_USER=${{ secrets.DB_USER }} >> .env
          echo DB_PASSWORD=${{ secrets.DB_PASSWORD }} >> .env
          echo DB_DATABASE=${{ secrets.DB_DATABASE }} >> .env

      - name: Docker up
        run: docker compose up --build -d

      - name: Wait for the docker build to run
        run: sleep 60

      - name: Test the running api
        run: |
          curl http://localhost:3000/releases